name = "sevii"
version = "1.0.0"
target = "javascript"

[javascript]
runtime = "node"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_aws_node = { path = "../gleam_aws_node" }
conversation = ">= 1.4.3 and < 2.0.0"
glen = ">= 2.2.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_javascript = ">= 0.12.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
