name = "hello_world"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
sevii = { path = "../.." }
gleam_javascript = ">= 0.13.0 and < 1.0.0"
glen = ">= 2.2.0 and < 3.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "deno"
